apiVersion: v1
kind: Pod
metadata:
  name: "catalogapi"
  namespace: default
  labels:
    app: "catalogapi"
spec:
  containers:
  - name: catalogapi
    image: "satish860/eshoponweb-catalogapi:v39"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always