version: '3.4'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'


  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - '6379:6379'
   
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
   
  rabbitmq:
     container_name: rabbitmq
     restart: always
     ports:
        - "5672:5672"
        - "15672:15672"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
    ports:
      - '8080:80'
    depends_on:
      - catalogdb

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379
      - GrpcSettings__DiscountUrl=http://discount.grpc
      - Rabbitmq__HostUrl=amqp://guest:guest@rabbitmq:5672
    ports:
      - '8081:80'
    depends_on:
        - basketdb
        - discount.grpc

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Marten=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
    ports:
      - "8082:80"
    depends_on:
        - discountdb


  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Marten=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;
    ports:
      - "8083:80"
      - "400:443"
    depends_on:
        - discountdb
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - Rabbitmq__HostUrl=amqp://guest:guest@rabbitmq:5672
    ports:
      - "8084:80"
    depends_on:
      - catalogdb


  reverseproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"
    depends_on:
        - catalog.api
  
  elasticsearch:
   container_name: elasticsearch
   restart: always
   ports:
     - '9200:9200'
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    depends_on: 
      - elasticsearch
    ports:
       - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
