version: '3.4'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'


  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - '6379:6379'
   
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabaseSettings:ConnectionString=mongodb://catalogdb:27017'
    ports:
      - '8080:80'
    depends_on:
      - catalogdb

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString = basketdb:6379"
    ports:
      - '8081:80'
    depends_on:
        - basketdb

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8082:80"
    depends_on:
        - discountdb

