name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/EShopOnweb.sln
    - name: Build
      run: dotnet build --no-restore ./src/EShopOnweb.sln
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Catalog API
      uses: docker/build-push-action@v2.9.0
      with:
        context: src/
        push: true
        file: src/Services/Catalog/Catalog.Api/Dockerfile
        tags: satish860/eshoponweb-catalogapi:v${{ github.run_number }}
    - name: Build basket API
      uses: docker/build-push-action@v2.9.0
      with:
        context: src/
        push: true
        file: src/Services/Basket/Basket.Api/Dockerfile
        tags: satish860/eshoponweb-basketapi:v${{ github.run_number }}
